services:
  api:
    build: .
    container_name: auth-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge